In [94]:
import pandas as pd

# Reading customer and loan data

In [162]:
customer_data_path = '/Users/shiva/Downloads/masked_data/customer_details_masked_mar26.csv'
loan_data_path = '/Users/shiva/Downloads/masked_data/loan_details_masked_mar26.csv'

customer_data = pd.read_csv(customer_data_path)

In [166]:
customer_data.head()

,Unnamed: 0,fileno,customer_id,customer_name,customer_age,customer_type,gender,employment_status,customer_income,income_to_emi_ratio,customer_segment,prior_loans_count,prior_delinquency_history,customer_geography_type,caopp_data_flag,masked_loan_id
0,0,5043878,GLBCUST0000000168639,SOLAIAPPAN.P,NaN,P,NaN,NaN,NaN,NaN,Low,1.0,0,NaN,No,LN_nN4VGtIgQds=
1,1,5043880,GLBCUST0000000168642,KOTTAISAMY.I,NaN,P,NaN,NaN,NaN,NaN,Low,1.0,0,NaN,No,LN_f2TARzyVhng=
2,2,5043882,GLBCUST0000000168644,Dhanapakkiam NA R,NaN,P,NaN,NaN,NaN,NaN,Low,1.0,0,NaN,No,LN_L7pW6O0V8nQ=
3,3,5043883,GLBCUST0000000168645,ARIVALAGAN.A,NaN,P,NaN,NaN,NaN,NaN,Low,1.0,0,NaN,No,LN_NG-iatJWLAg=
4,4,5043892,GLBCUST0000000168654,BAKKIYA,NaN,P,NaN,NaN,NaN,NaN,Low,1.0,0,NaN,No,LN_wnF4F34dT98=

In [167]:
loan_data = pd.read_csv(loan_data_path)

In [170]:
loan_data.columns

Index(['Unnamed: 0', 'fileno', 'loan_origination_date',
       'scheduled_maturity_date', 'tenure_total', 'product_type',
       'secured_flag', 'interest_rate', 'emi_frequency', 'disbursed_amount',
       'principal_outstanding', 'ltv', 'bureau_score_origination',
       'restructured_flag', 'moratorium_flag', 'branch', 'state',
       'repayment_start_date', 'Sourcing channel', 'scheme', 'masked_loan_id'],
      dtype='str')

In [172]:
with pd.option_context('display.max_columns', None, 'display.max_rows', None):
    print(loan_data.head())

   Unnamed: 0   fileno loan_origination_date scheduled_maturity_date  \
0           0  5043878            2017-02-10              2028-07-31
1           1  5043880            2017-03-10              2032-03-31
2           2  5043882            2017-02-10              2026-10-31
3           3  5043883            2017-03-10              2028-05-31
4           4  5043892            2017-03-10              2027-08-31

   tenure_total product_type secured_flag  interest_rate emi_frequency  \
0           132      FSHL HL          Yes          17.00       Monthly
1           180      FSHL HL          Yes          17.00       Monthly
2           120      FSHL HL          Yes          16.25       Monthly
3           132      FSHL HL          Yes          16.75       Monthly
4           132      FSHL HL          Yes          17.00       Monthly

   disbursed_amount  principal_outstanding    ltv  bureau_score_origination  \
0          400000.0              185599.41  39.99                       NaN
1          900000.0              723319.40  39.99                       NaN
2          350000.0               79472.33  39.99                       NaN
3          400000.0              203986.86  39.99                       NaN
4          650000.0              202853.15  39.99                       NaN

  restructured_flag  moratorium_flag          branch state  \
0                No              1.0       Tuticorin    TN
1                No              1.0        Surandai    TN
2                No              1.0           Karur    TN
3                No              1.0           Karur    TN
4                No              1.0  Vasudevanallur    TN

  repayment_start_date Sourcing channel                  scheme  \
0           2017-03-10              NaN  FSHL Home Construction
1           2017-04-10              NaN  FSHL Home Construction
2           2017-03-10              NaN  FSHL Home Construction
3           2017-04-10              NaN  FSHL Home Construction
4           2017-04-10              NaN  FSHL Home Construction

    masked_loan_id
0  LN_nN4VGtIgQds=
1  LN_f2TARzyVhng=
2  LN_L7pW6O0V8nQ=
3  LN_NG-iatJWLAg=
4  LN_wnF4F34dT98=

# Payment data

In [173]:
bounce_data = '/Users/shiva/Downloads/masked_data/payment_bounce_data_masked_mar26.csv'

In [174]:
bounce_data = pd.read_csv(bounce_data)

/var/folders/fn/xcjmlh6119d7cxmd5kr0smw40000gn/T/ipykernel_59558/1835428962.py:1: DtypeWarning: Columns (0: closure date) have mixed types. Specify dtype option on import or set low_memory=False.
  bounce_data = pd.read_csv(bounce_data)

In [175]:
with pd.option_context('display.max_columns', None, 'display.max_rows', None):
    display(bounce_data.head())

,Unnamed: 0,file no,state,loan status,closure date,maturity date,Installment Number,Installment Due Date,communicated_installment_date,emi_amount,paid EMI,unpaid EMI,number_of_paid_emis,number_of_unpaid_emis,dpd (max),bucket_prior,bucket_current,Transaction Id,Receipt Id,Installment Due Date_y,Installment Amount,Transaction Date,Transaction Amount,Allocated Amount,Transaction Status,Payment Mode,Payment Sub Mode,Payment Source,rank,year,month,communicated_installment_date1,bounce_flag,Paid_till_T_plus_7,masked_loan_id
0,1,APP-319099,GJ,A,NaN,2032-04-30,11,2026-02-28,10.0,7236.0,7236.0,0.0,10,0,0.0,0.0,0.0,60485509.0,71501703.0,2026-02-28,7236.0,2026-02-11,7236.0,6736.0,C,ELECTRONIC_FUND_TRANSFER,NEFT,BBP,1,2026,2,2026-02-10,1,0,LN_GlRWLuleCfo=
1,3,APP-319099,GJ,A,NaN,2032-04-30,10,2026-01-31,10.0,7236.0,7236.0,0.0,10,0,0.0,0.0,0.0,60485508.0,69752882.0,2026-01-31,7236.0,2026-01-02,7236.0,6736.0,C,ELECTRONIC_FUND_TRANSFER,NEFT,BBP,1,2026,1,2026-01-10,0,0,LN_GlRWLuleCfo=
2,19,APP-327505,GJ,A,NaN,2032-05-31,10,2026-02-28,10.0,5997.0,5997.0,0.0,9,0,0.0,0.0,0.0,61550095.0,71531188.0,2026-02-28,5997.0,2026-02-13,5997.0,4994.0,C,ELECTRONIC_FUND_TRANSFER,NEFT,BBP,1,2026,2,2026-02-10,1,0,LN_YJDgotY4Ucc=
3,21,APP-327505,GJ,A,NaN,2032-05-31,9,2026-01-31,10.0,5997.0,5997.0,0.0,9,0,0.0,0.0,0.0,61550094.0,70071842.0,2026-01-31,5997.0,2026-01-10,5997.0,4994.0,C,ELECTRONIC_FUND_TRANSFER,SUB_PAYMENT_1,UPI,1,2026,1,2026-01-10,0,0,LN_YJDgotY4Ucc=
4,37,APP-328703,GJ,A,NaN,2032-05-31,10,2026-02-28,10.0,8364.0,8364.0,0.0,9,0,0.0,0.0,0.0,61716946.0,71441877.0,2026-02-28,8364.0,2026-02-10,8364.0,7864.0,C,ELECTRONIC_FUND_TRANSFER,NACH,NaN,1,2026,2,2026-02-10,0,0,LN_ifhPIOkwq74=

In [176]:
bounce_data.shape

(316934, 35)

In [177]:
bounce_data['masked_loan_id'].value_counts()

masked_loan_id
LN_l65WcrBLJVM=    3
LN_3EuByvosnOk=    3
LN_NHDYsRnC7Ns=    3
LN_AE4lpJ0a1Sc=    3
LN__xipWP0Xcy8=    3
                  ..
LN_dSXVQrwkJsg=    2
LN_uc8VHZWREAM=    2
LN_0styzOLZCkI=    2
LN__pl4lJFQmgY=    2
LN_gNcffGK0qnc=    2
Name: count, Length: 158461, dtype: int64

In [178]:
# Around 1.58 lakh loans

# Column sanity check

In [179]:
columns = ['Unnamed: 0', 'file no', 'state', 'loan status', 'closure date',
       'maturity date', 'Installment Number', 'Installment Due Date',
       'communicated_installment_date', 'emi_amount', 'paid EMI', 'unpaid EMI',
       'number_of_paid_emis', 'number_of_unpaid_emis', 'dpd (max)',
       'bucket_prior', 'bucket_current', 'Transaction Id', 'Receipt Id',
       'Installment Due Date_y', 'Installment Amount', 'Transaction Date',
       'Transaction Amount', 'Allocated Amount', 'Transaction Status',
       'Payment Mode', 'Payment Sub Mode', 'Payment Source', 'rank', 'year',
       'month', 'communicated_installment_date1', 'bounce_flag',
       'Paid_till_T_plus_7', 'masked_loan_id']

In [180]:
bounce_data.columns

Index(['Unnamed: 0', 'file no', 'state', 'loan status', 'closure date',
       'maturity date', 'Installment Number', 'Installment Due Date',
       'communicated_installment_date', 'emi_amount', 'paid EMI', 'unpaid EMI',
       'number_of_paid_emis', 'number_of_unpaid_emis', 'dpd (max)',
       'bucket_prior', 'bucket_current', 'Transaction Id', 'Receipt Id',
       'Installment Due Date_y', 'Installment Amount', 'Transaction Date',
       'Transaction Amount', 'Allocated Amount', 'Transaction Status',
       'Payment Mode', 'Payment Sub Mode', 'Payment Source', 'rank', 'year',
       'month', 'communicated_installment_date1', 'bounce_flag',
       'Paid_till_T_plus_7', 'masked_loan_id'],
      dtype='str')

In [181]:
bounce_data.columns == columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [182]:
if list(bounce_data.columns) == list(columns):
    print("Pass")
else:
    print("Fail")

Pass

In [183]:
bounce_data[bounce_data['communicated_installment_date1'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, file no, state, loan status, closure date, maturity date, Installment Number, Installment Due Date, communicated_installment_date, emi_amount, paid EMI, unpaid EMI, number_of_paid_emis, number_of_unpaid_emis, dpd (max), bucket_prior, bucket_current, Transaction Id, Receipt Id, Installment Due Date_y, Installment Amount, Transaction Date, Transaction Amount, Allocated Amount, Transaction Status, Payment Mode, Payment Sub Mode, Payment Source, rank, year, month, communicated_installment_date1, bounce_flag, Paid_till_T_plus_7, masked_loan_id]
Index: []

[0 rows x 35 columns]

In [184]:
sample_loan_id = bounce_data.head()['masked_loan_id'].unique().tolist()[0]

In [185]:
with pd.option_context('display.max_columns', None, 
                       'display.max_rows', None,
                       'display.max_colwidth', None):
    display(bounce_data[bounce_data['masked_loan_id'] == sample_loan_id])

,Unnamed: 0,file no,state,loan status,closure date,maturity date,Installment Number,Installment Due Date,communicated_installment_date,emi_amount,paid EMI,unpaid EMI,number_of_paid_emis,number_of_unpaid_emis,dpd (max),bucket_prior,bucket_current,Transaction Id,Receipt Id,Installment Due Date_y,Installment Amount,Transaction Date,Transaction Amount,Allocated Amount,Transaction Status,Payment Mode,Payment Sub Mode,Payment Source,rank,year,month,communicated_installment_date1,bounce_flag,Paid_till_T_plus_7,masked_loan_id
0,1,APP-319099,GJ,A,NaN,2032-04-30,11,2026-02-28,10.0,7236.0,7236.0,0.0,10,0,0.0,0.0,0.0,60485509.0,71501703.0,2026-02-28,7236.0,2026-02-11,7236.0,6736.0,C,ELECTRONIC_FUND_TRANSFER,NEFT,BBP,1,2026,2,2026-02-10,1,0,LN_GlRWLuleCfo=
1,3,APP-319099,GJ,A,NaN,2032-04-30,10,2026-01-31,10.0,7236.0,7236.0,0.0,10,0,0.0,0.0,0.0,60485508.0,69752882.0,2026-01-31,7236.0,2026-01-02,7236.0,6736.0,C,ELECTRONIC_FUND_TRANSFER,NEFT,BBP,1,2026,1,2026-01-10,0,0,LN_GlRWLuleCfo=

# Combine with older payment data

In [186]:
path = '/Users/shiva/Downloads/Fivestar_data_models_and_notebooks/Data/payment_bounce_data_masked_corrected.csv'
previous_bounce_data = pd.read_csv(path)

/var/folders/fn/xcjmlh6119d7cxmd5kr0smw40000gn/T/ipykernel_59558/3872820532.py:2: DtypeWarning: Columns (0: file no) have mixed types. Specify dtype option on import or set low_memory=False.
  previous_bounce_data = pd.read_csv(path)

In [187]:
previous_bounce_data.shape

(18776843, 35)

In [188]:
if list(previous_bounce_data.columns) == list(columns):
    print("Pass")
else:
    print("Fail")

Pass

In [189]:
# Take unique masked_loan_id from the mar 26 data
# Use it to filter the previous_bounce_data to give previous_bounce_data_filtered
# Concant previous_bounce_data_filtered and bounce to give combined_bounce df
# bounce_data[bounce_data['masked_loan_id']

In [190]:
# Take unique masked_loan_id from the mar 26 data
mar26_loan_ids = bounce_data['masked_loan_id'].unique()

# Use it to filter the previous_bounce_data
previous_bounce_data_filtered = previous_bounce_data[
    previous_bounce_data['masked_loan_id'].isin(mar26_loan_ids)
]

# Concat previous_bounce_data_filtered and bounce to give combined_bounce df
combined_bounce = pd.concat([previous_bounce_data_filtered, bounce_data], ignore_index=True)

In [191]:
print(len(bounce_data['masked_loan_id'].unique()))
print(len(previous_bounce_data_filtered['masked_loan_id'].unique()))
print(len(combined_bounce['masked_loan_id'].unique()))

158461
158442
158461

In [192]:
previous_bounce_data.columns

Index(['Unnamed: 0', 'file no', 'state', 'loan status', 'closure date',
       'maturity date', 'Installment Number', 'Installment Due Date',
       'communicated_installment_date', 'emi_amount', 'paid EMI', 'unpaid EMI',
       'number_of_paid_emis', 'number_of_unpaid_emis', 'dpd (max)',
       'bucket_prior', 'bucket_current', 'Transaction Id', 'Receipt Id',
       'Installment Due Date_y', 'Installment Amount', 'Transaction Date',
       'Transaction Amount', 'Allocated Amount', 'Transaction Status',
       'Payment Mode', 'Payment Sub Mode', 'Payment Source', 'rank', 'year',
       'month', 'communicated_installment_date1', 'bounce_flag',
       'Paid_till_T_plus_7', 'masked_loan_id'],
      dtype='str')

In [193]:
bounce_data.columns

Index(['Unnamed: 0', 'file no', 'state', 'loan status', 'closure date',
       'maturity date', 'Installment Number', 'Installment Due Date',
       'communicated_installment_date', 'emi_amount', 'paid EMI', 'unpaid EMI',
       'number_of_paid_emis', 'number_of_unpaid_emis', 'dpd (max)',
       'bucket_prior', 'bucket_current', 'Transaction Id', 'Receipt Id',
       'Installment Due Date_y', 'Installment Amount', 'Transaction Date',
       'Transaction Amount', 'Allocated Amount', 'Transaction Status',
       'Payment Mode', 'Payment Sub Mode', 'Payment Source', 'rank', 'year',
       'month', 'communicated_installment_date1', 'bounce_flag',
       'Paid_till_T_plus_7', 'masked_loan_id'],
      dtype='str')

# Creating bounce features

In [194]:
import pandas as pd
from datetime import datetime


bounce_data['communicated_installment_date1'] = pd.to_datetime(
    bounce_data['communicated_installment_date1']
)

def bounces_in_window(df, loan_col, date_col, flag_col, days, as_of_date):
    cutoff = as_of_date - pd.Timedelta(days=days)
    window = df[df[date_col] >= cutoff]
    return window.groupby(loan_col)[flag_col].sum().rename(f'bounces_last_{days}d')

AS_OF_DATE = datetime(2026, 4, 1)

hist = bounce_data[
    (bounce_data['year'] < 2026) |
    ((bounce_data['year'] == 2026) & (bounce_data['month'] < 4))
].copy()

target_month = bounce_data[
    (bounce_data['year'] == 2026) & (bounce_data['month'] == 4)
].copy()

# ── FEATURES ──────────────────────────────────────────────────────
features = pd.DataFrame(index=bounce_data['masked_loan_id'].unique())
for days in [30, 60, 90, 180, 270]:
    feat = bounces_in_window(
        hist, 'masked_loan_id',
        'communicated_installment_date1',
        'bounce_flag',
        days, AS_OF_DATE
    )
    features = features.join(feat, how='left')

features = (
    features
    .fillna(0)
    .reset_index()
    .rename(columns={'index': 'masked_loan_id'})
)

# # ── TARGET ────────────────────────────────────────────────────────
# target = target_month[['masked_loan_id', 'Paid_till_T_plus_7']].rename(
#     columns={'Paid_till_T_plus_7': 'target_bounce'}
# )

# model_df = features.merge(target, on='masked_loan_id', how='inner')
# model_df['as_of_month']   = 'Apr-2026'
# model_df['target_bounce'] = model_df['target_bounce'].fillna(0).astype(int)

# print(model_df.shape)
# print(model_df['target_bounce'].value_counts())

In [129]:
features

,masked_loan_id,bounces_last_30d,bounces_last_60d,bounces_last_90d,bounces_last_180d,bounces_last_270d
0,LN_GlRWLuleCfo=,0.0,1,1,1,1
1,LN_YJDgotY4Ucc=,0.0,1,1,1,2
2,LN_ifhPIOkwq74=,0.0,0,0,1,1
3,LN_GmK89VbaOag=,0.0,0,0,0,0
4,LN__Pd6aMOmhbY=,0.0,0,0,0,0
...,...,...,...,...,...,...
158456,LN_-EXIn-zTNq0=,0.0,1,2,2,2
158457,LN_gRTEvo6r2Ls=,0.0,1,2,2,2
158458,LN_wsaBWP61kAQ=,0.0,1,2,2,2
158459,LN_2UGOArBhYQ0=,0.0,0,0,0,0
158460,LN_SMC27cNuoXM=,0.0,0,1,1,1

In [195]:
# mapper_df = pd.read_csv(f'{BASE_PATH}/mapper_df.csv')
# model_df  = features.merge(mapper_df, on='masked_loan_id', how='left')

In [196]:
# print(model_df.groupby('as_of_month')['target_bounce'].value_counts(1).unstack(fill_value=0))

In [199]:
bounce_features = features.to_csv('/Users/shiva/Downloads/Fivestar_data_models_and_notebooks/Data/inference_bounce_features.csv',index=False)

In [200]:
features

,masked_loan_id,bounces_last_30d,bounces_last_60d,bounces_last_90d,bounces_last_180d,bounces_last_270d
0,LN_GlRWLuleCfo=,0.0,1,1,1,1
1,LN_YJDgotY4Ucc=,0.0,1,1,1,1
2,LN_ifhPIOkwq74=,0.0,0,0,0,0
3,LN_GmK89VbaOag=,0.0,0,0,0,0
4,LN__Pd6aMOmhbY=,0.0,0,0,0,0
...,...,...,...,...,...,...
158456,LN_dSXVQrwkJsg=,0.0,0,0,0,0
158457,LN_uc8VHZWREAM=,0.0,0,0,0,0
158458,LN_0styzOLZCkI=,0.0,0,1,1,1
158459,LN__pl4lJFQmgY=,0.0,0,0,0,0
158460,LN_gNcffGK0qnc=,0.0,0,0,0,0

# Creating bureau features : Account data

In [201]:
bureau_data = '/Users/shiva/Downloads/masked_data/accnt_masked_mar26.csv'

In [202]:
df = pd.read_csv(bureau_data)

In [203]:
df.head()

,Unnamed: 0,CREDT-RPT-ID,LOS-APP-ID,CANDIDATE - ID,CUSTOMER ID/MBR ID,BRANCH,KENDRA,SELF-INDICATOR,MATCH-TYPE,ACC-NUM,...,CUR BAL - HIST,DAS - HIST,AMT OVERDUE - HIST,AMT PAID - HIST,INCOME,INCOME INDICATOR,TENURE,OCCUPATION,Unnamed: 41,masked_loan_id
0,0,FIVE260323CR3780056846279244,FSTNLALONS000005708289_O02_5960290216,6120920695,NaN,NaN,NaN,True,PRIMARY,FSTNLALONS000005708289,...,"381119,383439,385713,387945,390136,392286,3943...",S04S04S04S04S04S04S04S04S04S04,"0,0,0,0,0,0,0,0,0,0,",",,,,,,,,,,",0.0,NaN,84.0,NaN,NaN,LN_phi3RmKYivk=
1,1,FIVE260323CR3780056846279244,FSTNLALONS000005708289_O02_5960290216,6816500961,NaN,IN0010367,3709198,False,PRIMARY,XXXX,...,"0,10214,12671,15087,17463,19801,23235,25477,27...",S07S04S04S04S04S04S04S04S04S04S04S04S04S04S04S...,"0,0,,,,,,,,,0,,,,,,,,,,,,",",",25000.0,M,NaN,NaN,NaN,LN_phi3RmKYivk=
2,2,FIVE260323CR3780056846279244,FSTNLALONS000005708289_O02_5960290216,6082027236,NaN,NaN,NaN,False,PRIMARY,XXXX,...,"42540,43301,44801,46274,",S04S04S04S04,",,,,",",,,,",0.0,NaN,52.0,NaN,NaN,LN_phi3RmKYivk=
3,3,FIVE260323CR1872056846279244,FSTNLALONS000005724149_O02_6036915109,7666185511,NaN,KALIYAKKAVILAI MML,ML0059S02C0101,False,PRIMARY,XXXX,...,"0,14165,15978,17760,19512,21235,22929,24491,26...",S07S04S04S04S04S04S04S04S04S04S04S04XXXS04S04S...,"0,0,0,0,0,0,0,0,0,0,0,0,,0,0,0,0,0,0,0,",",",24500.0,M,NaN,NaN,NaN,LN_PluzUzO-Um4=
4,4,FIVE260323CR1872056846279244,FSTNLALONS000005724149_O02_6036915109,6388293864,NaN,NaN,NaN,False,PRIMARY,XXXX,...,"9452,9452,9452,9452,9452,9452,12395,12395,1521...",S05S05S05S05S05S05S05S04S04S04S04S04S04S04S04S...,"9510,9510,9510,9510,6340,3170,3170,0,0,0,0,0,0...",",,,,,,,,,,,,,,,,,,,,,,,,,,,,",773760.0,A,24.0,OTHERS,NaN,LN_PluzUzO-Um4=

In [204]:
df.columns

Index(['Unnamed: 0', 'CREDT-RPT-ID', 'LOS-APP-ID', 'CANDIDATE - ID',
       'CUSTOMER ID/MBR ID', 'BRANCH', 'KENDRA', 'SELF-INDICATOR',
       'MATCH-TYPE', 'ACC-NUM', 'CREDIT-GRANTOR', 'ACCT-TYPE',
       'CONTRIBUTOR-TYPE', 'DATE-REPORTED', 'OWNERSHIP-IND', 'ACCOUNT-STATUS',
       'DISBURSED-DT', 'CLOSE-DT', 'LAST-PAYMENT-DATE',
       'CREDIT-LIMIT/SANC AMT', ' DISBURSED-AMT/HIGH CREDIT',
       ' INSTALLMENT-AMT', ' CURRENT-BAL', 'INSTALLMENT-FREQUENCY',
       'WRITE-OFF-DATE', ' OVERDUE-AMT', ' WRITE-OFF-AMT', 'ASSET_CLASS',
       ' ACCOUNT-REMARKS', 'LINKED-ACCOUNTS', 'REPORTED DATE - HIST ',
       'DPD - HIST', 'ASSET CLASS - HIST ', 'HIGH CRD - HIST ',
       'CUR BAL - HIST ', 'DAS - HIST ', 'AMT OVERDUE - HIST ',
       'AMT PAID - HIST ', 'INCOME ', ' INCOME INDICATOR ', 'TENURE ',
       ' OCCUPATION', 'Unnamed: 41', 'masked_loan_id'],
      dtype='str')

In [205]:
# Show all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Reset to defaults
df.head()

,Unnamed: 0,CREDT-RPT-ID,LOS-APP-ID,CANDIDATE - ID,CUSTOMER ID/MBR ID,BRANCH,KENDRA,SELF-INDICATOR,MATCH-TYPE,ACC-NUM,CREDIT-GRANTOR,ACCT-TYPE,CONTRIBUTOR-TYPE,DATE-REPORTED,OWNERSHIP-IND,ACCOUNT-STATUS,DISBURSED-DT,CLOSE-DT,LAST-PAYMENT-DATE,CREDIT-LIMIT/SANC AMT,DISBURSED-AMT/HIGH CREDIT,INSTALLMENT-AMT,CURRENT-BAL,INSTALLMENT-FREQUENCY,WRITE-OFF-DATE,OVERDUE-AMT,WRITE-OFF-AMT,ASSET_CLASS,ACCOUNT-REMARKS,LINKED-ACCOUNTS,REPORTED DATE - HIST,DPD - HIST,ASSET CLASS - HIST,HIGH CRD - HIST,CUR BAL - HIST,DAS - HIST,AMT OVERDUE - HIST,AMT PAID - HIST,INCOME,INCOME INDICATOR,TENURE,OCCUPATION,Unnamed: 41,masked_loan_id
0,0,FIVE260323CR3780056846279244,FSTNLALONS000005708289_O02_5960290216,6120920695,NaN,NaN,NaN,True,PRIMARY,FSTNLALONS000005708289,FIVE STAR BUSINESS FINANCE LIMITED,Property Loan,NBF,28-02-2026,Joint,Active,29-05-2025,NaN,10-02-2026,NaN,"4,00,000","9,500/Monthly","3,81,119",F03,NaN,0,0,Standard,NaN,,"20260228,20260131,20251231,20251130,20251031,20250930,20250831,20250731,20250630,20250531,",000000000000000000000000000000,L01L01L01L01L01L01L01L01L01L01,"400000,400000,400000,400000,400000,400000,400000,400000,400000,400000,","381119,383439,385713,387945,390136,392286,394397,396470,398504,400500,",S04S04S04S04S04S04S04S04S04S04,"0,0,0,0,0,0,0,0,0,0,",",,,,,,,,,,",0.0,NaN,84.0,NaN,NaN,LN_phi3RmKYivk=
1,1,FIVE260323CR3780056846279244,FSTNLALONS000005708289_O02_5960290216,6816500961,NaN,IN0010367,3709198,False,PRIMARY,XXXX,XXXX,JLG Individual,MFI,28-02-2026,Primary,Closed,21-03-2024,04-12-2025,03-12-2025,"55,000","55,000","1,329/BiWeekly",0,F02,NaN,0,0,NaN,NaN,,"20251231,20251130,20251031,20250930,20250831,20250731,20250630,20250531,20250430,20250331,20250215,20250131,20241231,20241130,20241031,20240930,20240831,20240731,20240630,20240531,20240430,20240331,",000000000000000000000000000000000000000000000000000000000000000000,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,",","0,10214,12671,15087,17463,19801,23235,25477,27682,29851,33038,34082,37165,39178,41157,43104,45019,46902,49669,51476,53252,55000,",S07S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04,"0,0,,,,,,,,,0,,,,,,,,,,,,",",",25000.0,M,NaN,NaN,NaN,LN_phi3RmKYivk=
2,2,FIVE260323CR3780056846279244,FSTNLALONS000005708289_O02_5960290216,6082027236,NaN,NaN,NaN,False,PRIMARY,XXXX,XXXX,Business Loan General,MFI,15-03-2026,Individual,Active,04-12-2025,NaN,25-02-2026,NaN,"47,000","1,159/Monthly","42,540",F03,NaN,NaN,0,Standard,NaN,,"20260315,20260228,20260131,20251231,",000000000000,L01L01L01L01,"47000,47000,47000,47000,","42540,43301,44801,46274,",S04S04S04S04,",,,,",",,,,",0.0,NaN,52.0,NaN,NaN,LN_phi3RmKYivk=
3,3,FIVE260323CR1872056846279244,FSTNLALONS000005724149_O02_6036915109,7666185511,NaN,KALIYAKKAVILAI MML,ML0059S02C0101,False,PRIMARY,XXXX,XXXX,JLG Individual,MFI,29-02-2024,Primary,Closed,25-05-2022,06-12-2023,08-11-2023,"40,000","40,000","2,090/Monthly",0,F03,NaN,0,0,NaN,NaN,,"20231231,20231109,20231010,20230916,20230817,20230719,20230622,20230518,20230420,20230316,20230217,20230112,20221201,20221130,20221031,20220930,20220831,20220731,20220630,20220531,",000000000000000000000000000000000000XXX000000000000000000000,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,",","0,14165,15978,17760,19512,21235,22929,24491,26130,27624,29210,32301,,33665,35148,36606,37879,39291,40000,40000,",S07S04S04S04S04S04S04S04S04S04S04S04XXXS04S04S04S04S04S04S04,"0,0,0,0,0,0,0,0,0,0,0,0,,0,0,0,0,0,0,0,",",",24500.0,M,NaN,NaN,NaN,LN_PluzUzO-Um4=
4,4,FIVE260323CR1872056846279244,FSTNLALONS000005724149_O02_6036915109,6388293864,NaN,NaN,NaN,False,PRIMARY,XXXX,XXXX,Business Loan Unsecured,MFI,15-03-2026,Individual,Delinquent,06-12-2023,NaN,23-10-2025,NaN,"60,000","3,170/Monthly","9,452",F03,NaN,"9,510",0,NaN,NaN,,"20260315,20260228,20260131,20251231,20251130,20251031,20250930,20250831,20250731,20250630,20250531,20250430,20250331,20250228,20250131,20241231,20241130,20241031,20240930,20240831,20240701,20240630,20240531,20240430,20240331,20240229,20240131,20231231,",158143115084053023020000000000000000000000000000000000000000XXX000000000000000000000,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,"60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,,60000,60000,60000,60000,60000,60000,60000,","9452,9452,9452,9452,9452,9452,12395,12395,15216,18055,20843,23475,26165,28807,31261,33811,36315,38600,41018,43392,,47812,49840,52056,54232,56369,58205,58205,",S05S05S05S05S05S05S05S04S04S04S04S04S04S04S04S04S04S04S04S04XXXS04S04S04S04S04S04S04,"9510,9510,9510,9510,6340,3170,3170,0,0,0,0,0,0,0,0,0,0,0,0,0,,0,0,0,0,0,0,0,",",,,,,,,,,,,,,,,,,,,,,,,,,,,,",773760.0,A,24.0,OTHERS,NaN,LN_PluzUzO-Um4=

In [206]:
def extract_los_parts(df):
    """Extract loan_number, applicant_type, person_id from LOS-APP-ID."""
    df['loan_number'] = df['LOS-APP-ID'].str.extract(r'^(.+?)_O0[123]_')
    df['applicant_type'] = df['LOS-APP-ID'].str.extract(r'_(O0[123])_')
    df['person_id'] = df['LOS-APP-ID'].str.extract(r'_O0[123]_(\d+)$')
    return df

In [207]:
bureau = extract_los_parts(df)

# Add human-readable applicant role label
applicant_role_map = {'O01': 'Primary Applicant', 'O02': 'Co-Applicant', 'O03': 'Guarantor'}
bureau['applicant_role'] = bureau['applicant_type'].map(applicant_role_map)

In [208]:
bureau.head()

,Unnamed: 0,CREDT-RPT-ID,LOS-APP-ID,CANDIDATE - ID,CUSTOMER ID/MBR ID,BRANCH,KENDRA,SELF-INDICATOR,MATCH-TYPE,ACC-NUM,CREDIT-GRANTOR,ACCT-TYPE,CONTRIBUTOR-TYPE,DATE-REPORTED,OWNERSHIP-IND,ACCOUNT-STATUS,DISBURSED-DT,CLOSE-DT,LAST-PAYMENT-DATE,CREDIT-LIMIT/SANC AMT,DISBURSED-AMT/HIGH CREDIT,INSTALLMENT-AMT,CURRENT-BAL,INSTALLMENT-FREQUENCY,WRITE-OFF-DATE,OVERDUE-AMT,WRITE-OFF-AMT,ASSET_CLASS,ACCOUNT-REMARKS,LINKED-ACCOUNTS,REPORTED DATE - HIST,DPD - HIST,ASSET CLASS - HIST,HIGH CRD - HIST,CUR BAL - HIST,DAS - HIST,AMT OVERDUE - HIST,AMT PAID - HIST,INCOME,INCOME INDICATOR,TENURE,OCCUPATION,Unnamed: 41,masked_loan_id,loan_number,applicant_type,person_id,applicant_role
0,0,FIVE260323CR3780056846279244,FSTNLALONS000005708289_O02_5960290216,6120920695,NaN,NaN,NaN,True,PRIMARY,FSTNLALONS000005708289,FIVE STAR BUSINESS FINANCE LIMITED,Property Loan,NBF,28-02-2026,Joint,Active,29-05-2025,NaN,10-02-2026,NaN,"4,00,000","9,500/Monthly","3,81,119",F03,NaN,0,0,Standard,NaN,,"20260228,20260131,20251231,20251130,20251031,20250930,20250831,20250731,20250630,20250531,",000000000000000000000000000000,L01L01L01L01L01L01L01L01L01L01,"400000,400000,400000,400000,400000,400000,400000,400000,400000,400000,","381119,383439,385713,387945,390136,392286,394397,396470,398504,400500,",S04S04S04S04S04S04S04S04S04S04,"0,0,0,0,0,0,0,0,0,0,",",,,,,,,,,,",0.0,NaN,84.0,NaN,NaN,LN_phi3RmKYivk=,FSTNLALONS000005708289,O02,5960290216,Co-Applicant
1,1,FIVE260323CR3780056846279244,FSTNLALONS000005708289_O02_5960290216,6816500961,NaN,IN0010367,3709198,False,PRIMARY,XXXX,XXXX,JLG Individual,MFI,28-02-2026,Primary,Closed,21-03-2024,04-12-2025,03-12-2025,"55,000","55,000","1,329/BiWeekly",0,F02,NaN,0,0,NaN,NaN,,"20251231,20251130,20251031,20250930,20250831,20250731,20250630,20250531,20250430,20250331,20250215,20250131,20241231,20241130,20241031,20240930,20240831,20240731,20240630,20240531,20240430,20240331,",000000000000000000000000000000000000000000000000000000000000000000,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,",","0,10214,12671,15087,17463,19801,23235,25477,27682,29851,33038,34082,37165,39178,41157,43104,45019,46902,49669,51476,53252,55000,",S07S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04S04,"0,0,,,,,,,,,0,,,,,,,,,,,,",",",25000.0,M,NaN,NaN,NaN,LN_phi3RmKYivk=,FSTNLALONS000005708289,O02,5960290216,Co-Applicant
2,2,FIVE260323CR3780056846279244,FSTNLALONS000005708289_O02_5960290216,6082027236,NaN,NaN,NaN,False,PRIMARY,XXXX,XXXX,Business Loan General,MFI,15-03-2026,Individual,Active,04-12-2025,NaN,25-02-2026,NaN,"47,000","1,159/Monthly","42,540",F03,NaN,NaN,0,Standard,NaN,,"20260315,20260228,20260131,20251231,",000000000000,L01L01L01L01,"47000,47000,47000,47000,","42540,43301,44801,46274,",S04S04S04S04,",,,,",",,,,",0.0,NaN,52.0,NaN,NaN,LN_phi3RmKYivk=,FSTNLALONS000005708289,O02,5960290216,Co-Applicant
3,3,FIVE260323CR1872056846279244,FSTNLALONS000005724149_O02_6036915109,7666185511,NaN,KALIYAKKAVILAI MML,ML0059S02C0101,False,PRIMARY,XXXX,XXXX,JLG Individual,MFI,29-02-2024,Primary,Closed,25-05-2022,06-12-2023,08-11-2023,"40,000","40,000","2,090/Monthly",0,F03,NaN,0,0,NaN,NaN,,"20231231,20231109,20231010,20230916,20230817,20230719,20230622,20230518,20230420,20230316,20230217,20230112,20221201,20221130,20221031,20220930,20220831,20220731,20220630,20220531,",000000000000000000000000000000000000XXX000000000000000000000,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,",","0,14165,15978,17760,19512,21235,22929,24491,26130,27624,29210,32301,,33665,35148,36606,37879,39291,40000,40000,",S07S04S04S04S04S04S04S04S04S04S04S04XXXS04S04S04S04S04S04S04,"0,0,0,0,0,0,0,0,0,0,0,0,,0,0,0,0,0,0,0,",",",24500.0,M,NaN,NaN,NaN,LN_PluzUzO-Um4=,FSTNLALONS000005724149,O02,6036915109,Co-Applicant
4,4,FIVE260323CR1872056846279244,FSTNLALONS000005724149_O02_6036915109,6388293864,NaN,NaN,NaN,False,PRIMARY,XXXX,XXXX,Business Loan Unsecured,MFI,15-03-2026,Individual,Delinquent,06-12-2023,NaN,23-10-2025,NaN,"60,000","3,170/Monthly","9,452",F03,NaN,"9,510",0,NaN,NaN,,"20260315,20260228,20260131,20251231,20251130,20251031,20250930,20250831,20250731,20250630,20250531,20250430,20250331,20250228,20250131,20241231,20241130,20241031,20240930,20240831,20240701,20240630,20240531,20240430,20240331,20240229,20240131,20231231,",158143115084053023020000000000000000000000000000000000000000XXX000000000000000000000,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,"60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,,60000,60000,60000,60000,60000,60000,60000,","9452,9452,9452,9452,9452,9452,12395,12395,15216,18055,20843,23475,26165,28807,31261,33811,36315,38600,41018,43392,,47812,49840,52056,54232,56369,58205,58205,",S05S05S05S05S05S05S05S04S04S04S04S04S04S04S04S04S04S04S04S04XXXS04S04S04S04S04S04S04,"9510,9510,9510,9510,6340,3170,3170,0,0,0,0,0,0,0,0,0,0,0,0,0,,0,0,0,0,0,0,0,",",,,,,,,,,,,,,,,,,,,,,,,,,,,,",773760.0,A,24.0,OTHERS,NaN,LN_PluzUzO-Um4=,FSTNLALONS000005724149,O02,6036915109,Co-Applicant

In [209]:
master_O01 = bureau[bureau['applicant_type'] == 'O01'].copy()
# Filtering only primary

In [210]:
master_O01.shape

(2317869, 48)

In [211]:
master_O01 = master_O01.rename(columns={
    'ACCT-TYPE'                  : 'acct_type',
    'ACCOUNT-STATUS'             : 'account_status',
    'ASSET_CLASS'                : 'asset_class',
    ' OVERDUE-AMT'               : 'overdue_amt',
    ' CURRENT-BAL'               : 'current_bal',
    ' DISBURSED-AMT/HIGH CREDIT' : 'disbursed_amt',
    'REPORTED DATE - HIST '      : 'date_hist',   # trailing space
    'DPD - HIST'                 : 'dpd_hist',
})

print(f"master_O01: {master_O01.shape}")

master_O01: (2317869, 48)

In [215]:
len(master_O01['loan_number'].unique())

157561

In [216]:
len(features)

158461

# Create bureau features

In [217]:
import pandas as pd
import numpy as np
import gc

BASE_PATH = '/Users/shiva/Downloads/Five_star_customer_data'

# ============================================================
# LOAN TYPE MAPPING
# ============================================================
UNSECURED_TYPES = [
    'Personal Loan', 'Business Loan Unsecured', 'Business Loan General',
    'JLG Individual', 'JLG Group', 'SHG Individual', 'Consumer Loan',
    'Credit Card', 'Kisan Credit Card', 'Microfinance Others',
    'Microfinance Business Loan', 'Microfinance Personal Loan',
    'Business Loan Priority Sector  Agriculture',
    'Business Loan Priority Sector  Small Business',
    'Mudra Loans - Shishu / Kishor / Tarun',
    'Loan to Professional', 'Individual', 'Other',
]
SECURED_TYPES = [
    'Property Loan', 'Housing Loan', 'Auto Loan (Personal)', 'Gold Loan',
    'Two-Wheeler Loan', 'Business Loan - Secured', 'Commercial Vehicle Loan',
    'Tractor Loan', 'Loan Against Bank Deposits',
    'Loan Against Shares / Securities', 'Secured Credit Card', 'Overdraft',
]

def classify_loan_type(acct_type):
    if pd.isna(acct_type): return 'Unknown'
    if acct_type in SECURED_TYPES:   return 'Secured'
    if acct_type in UNSECURED_TYPES: return 'Unsecured'
    return 'Unknown'

AS_OF_DATE  = pd.Timestamp('2026-04-01')
AS_OF_LABEL = 'Apr-2026'

# ============================================================
# STEP 1: Slim bureau to only loans in model_df
# ============================================================
print("Step 1: Slimming bureau...")
# valid_loans = model_df['loan_number'].dropna().unique()
bureau_slim = master_O01[[
    'loan_number', 'acct_type', 'ACC-NUM',
    'CREDIT-GRANTOR', 'DISBURSED-DT', 'date_hist', 'dpd_hist',
]].copy()
bureau_slim['loan_type_tag'] = bureau_slim['acct_type'].apply(classify_loan_type)
bureau_slim['DISBURSED-DT']  = pd.to_datetime(
    bureau_slim['DISBURSED-DT'], format='%d-%m-%Y', errors='coerce'
)
print(f"bureau_slim         : {bureau_slim.shape}")
print(f"Loan type dist:\n{bureau_slim['loan_type_tag'].value_counts()}")

# ============================================================
# STEP 2: Parse DPD-HIST → long format
# ============================================================
print("\nStep 2: Parsing DPD-HIST to long format...")
sub = bureau_slim.dropna(subset=['dpd_hist', 'date_hist']).copy()
sub['date_list'] = sub['date_hist'].str.split(',').apply(
    lambda x: [i.strip() for i in x if i.strip()]
)
sub['dpd_list'] = sub['dpd_hist'].apply(
    lambda x: [str(x)[i:i+3] for i in range(0, len(str(x)), 3)]
)
sub = sub[sub['dpd_list'].str.len() == sub['date_list'].str.len()].copy()
print(f"  Rows after length filter: {len(sub):,}")

sub = sub.explode(['dpd_list', 'date_list'])
sub['report_date'] = pd.to_datetime(
    sub['date_list'].str.strip(), format='%Y%m%d', errors='coerce'
)
sub = sub.dropna(subset=['report_date'])

sub['is_active_month'] = (sub['dpd_list'] != 'XXX').astype(int)
sub['dpd_value'] = pd.to_numeric(
    sub['dpd_list'].where(sub['dpd_list'] != 'XXX'), errors='coerce'
)
active = sub['is_active_month'] == 1
sub['1_30_dpd']     = ((active) & (sub['dpd_value'] >= 1)  & (sub['dpd_value'] <= 30)).astype(int)
sub['30_90_dpd']    = ((active) & (sub['dpd_value'] >= 31) & (sub['dpd_value'] <= 90)).astype(int)
sub['90_above_dpd'] = ((active) & (sub['dpd_value'] > 90)).astype(int)

sub['acct_uniq_id'] = (
    sub['loan_number'].astype(str)    + '_' +
    sub['ACC-NUM'].astype(str)         + '_' +
    sub['CREDIT-GRANTOR'].astype(str)  + '_' +
    sub['DISBURSED-DT'].astype(str)
)
long_df = sub[[
    'loan_number', 'acct_type', 'loan_type_tag', 'acct_uniq_id',
    'DISBURSED-DT', 'report_date', 'dpd_value', 'is_active_month',
    '1_30_dpd', '30_90_dpd', '90_above_dpd'
]].reset_index(drop=True)
del sub, bureau_slim
gc.collect()
print(f"  long_df shape    : {long_df.shape}")
print(f"  Unique loans     : {long_df['loan_number'].nunique():,}")
print(f"  DPD flag counts:\n{long_df[['1_30_dpd','30_90_dpd','90_above_dpd']].sum()}")

# ============================================================
# STEP 3-6: Feature computation for Apr-2026
# ============================================================
print(f"\nStep 3-6: Computing features as of {AS_OF_LABEL}...")
dpd_flags     = ['1_30_dpd', '30_90_dpd', '90_above_dpd']
product_types = ['All', 'Secured', 'Unsecured']
windows       = [12, 24]

loans_this_month = model_df['loan_number'].dropna().unique()

long_month = long_df[long_df['loan_number'].isin(loans_this_month)].copy()
long_month['months_before_as_of'] = (
    (AS_OF_DATE.year  - long_month['report_date'].dt.year) * 12 +
    (AS_OF_DATE.month - long_month['report_date'].dt.month)
)
long_month['as_of_month'] = AS_OF_LABEL

# Keep only history strictly before AS_OF_DATE
long_hist = long_month[long_month['months_before_as_of'] >= 0].copy()
del long_month
gc.collect()
print(f"  long_hist shape : {long_hist.shape}")

# ── Ever-DPD ──────────────────────────────────────────────────
ever_result = long_hist[['loan_number']].drop_duplicates().reset_index(drop=True)
ever_result['as_of_month'] = AS_OF_LABEL
for win in windows:
    win_df = long_hist[
        (long_hist['months_before_as_of'] < win) &
        (long_hist['is_active_month'] == 1)
    ]
    for product in product_types:
        temp = win_df if product == 'All' else \
               win_df[win_df['loan_type_tag'] == product]
        agg = (
            temp.groupby('loan_number')[dpd_flags]
            .max().fillna(0).astype(int).reset_index()
        )
        agg = agg.rename(columns={
            d: f'ever_{d}_{win}m_{product.lower()}' for d in dpd_flags
        })
        ever_result = ever_result.merge(agg, on='loan_number', how='left')
feat_cols_ever = [c for c in ever_result.columns if c not in ['loan_number', 'as_of_month']]
ever_result[feat_cols_ever] = ever_result[feat_cols_ever].fillna(0).astype(int)

# ── Percent-DPD ───────────────────────────────────────────────
pct_result = long_hist[['loan_number']].drop_duplicates().reset_index(drop=True)
pct_result['as_of_month'] = AS_OF_LABEL
for win in windows:
    win_df = long_hist[
        (long_hist['months_before_as_of'] < win) &
        (long_hist['is_active_month'] == 1)
    ].copy()
    for product in product_types:
        temp = win_df if product == 'All' else \
               win_df[win_df['loan_type_tag'] == product]
        if temp.empty:
            continue
        denom = (
            temp.groupby('loan_number')['is_active_month']
            .sum().reset_index()
            .rename(columns={'is_active_month': 'denom'})
        )
        for dpd in dpd_flags:
            col = f'percent_{dpd}_{win}m_{product.lower()}_Agg_month'
            numer = (
                temp.groupby('loan_number')[dpd]
                .sum().reset_index()
                .rename(columns={dpd: 'numer'})
            )
            m = numer.merge(denom, on='loan_number', how='left')
            m[col] = (m['numer'] / m['denom'].replace(0, np.nan)).fillna(0)
            pct_result = pct_result.merge(
                m[['loan_number', col]], on='loan_number', how='left'
            )
            pct_result[col] = pct_result[col].fillna(0)

# ── Collateral ────────────────────────────────────────────────
coll_result = long_hist[['loan_number']].drop_duplicates().reset_index(drop=True)
coll_result['as_of_month'] = AS_OF_LABEL
acct_df = (
    long_hist[['loan_number', 'acct_uniq_id', 'loan_type_tag', 'months_before_as_of']]
    .sort_values('months_before_as_of')
    .drop_duplicates(subset=['loan_number', 'acct_uniq_id'])
    .copy()
)
acct_df['is_collateral'] = (acct_df['loan_type_tag'] == 'Secured').astype(int)
acct_df['is_any_loan']   = 1
for win in windows:
    win_accts = acct_df[acct_df['months_before_as_of'].between(0, win - 1)]
    agg = (
        win_accts.groupby('loan_number')[['is_collateral', 'is_any_loan']]
        .sum().reset_index()
        .rename(columns={
            'is_collateral': f'collateral_loan_count_{win}m',
            'is_any_loan'  : f'total_loan_count_{win}m',
        })
    )
    agg[f'collateral_loan_pct_{win}m'] = (
        agg[f'collateral_loan_count_{win}m'] /
        agg[f'total_loan_count_{win}m'].replace(0, np.nan)
    ).fillna(0)
    coll_result = coll_result.merge(agg, on='loan_number', how='left')
coll_result = coll_result.fillna(0)

# ── Merge all feature blocks ───────────────────────────────────
feat_df = (
    ever_result
    .merge(pct_result,  on=['loan_number', 'as_of_month'], how='left')
    .merge(coll_result, on=['loan_number', 'as_of_month'], how='left')
    .fillna(0)
)
del long_hist, ever_result, pct_result, coll_result, acct_df
gc.collect()

feat_cols = [c for c in feat_df.columns if c not in ['loan_number', 'as_of_month']]
print(f"\nfeat_df        : {feat_df.shape}")
print(f"Total features : {len(feat_cols)}")

Step 1: Slimming bureau...
bureau_slim         : (2317869, 8)
Loan type dist:
loan_type_tag
Unsecured    1210828
Secured      1092389
Unknown        14652
Name: count, dtype: int64

Step 2: Parsing DPD-HIST to long format...
  Rows after length filter: 2,317,869
  long_df shape    : (31931187, 11)
  Unique loans     : 157,561
  DPD flag counts:
1_30_dpd         890877
30_90_dpd        744997
90_above_dpd    2172081
dtype: int64

Step 3-6: Computing features as of Apr-2026...
  long_hist shape : (31926870, 13)

feat_df        : (157542, 44)
Total features : 42

In [220]:
feat_df.head()

,loan_number,as_of_month,ever_1_30_dpd_12m_all,ever_30_90_dpd_12m_all,ever_90_above_dpd_12m_all,ever_1_30_dpd_12m_secured,ever_30_90_dpd_12m_secured,ever_90_above_dpd_12m_secured,ever_1_30_dpd_12m_unsecured,ever_30_90_dpd_12m_unsecured,ever_90_above_dpd_12m_unsecured,ever_1_30_dpd_24m_all,ever_30_90_dpd_24m_all,ever_90_above_dpd_24m_all,ever_1_30_dpd_24m_secured,ever_30_90_dpd_24m_secured,ever_90_above_dpd_24m_secured,ever_1_30_dpd_24m_unsecured,ever_30_90_dpd_24m_unsecured,ever_90_above_dpd_24m_unsecured,percent_1_30_dpd_12m_all_Agg_month,percent_30_90_dpd_12m_all_Agg_month,percent_90_above_dpd_12m_all_Agg_month,percent_1_30_dpd_12m_secured_Agg_month,percent_30_90_dpd_12m_secured_Agg_month,percent_90_above_dpd_12m_secured_Agg_month,percent_1_30_dpd_12m_unsecured_Agg_month,percent_30_90_dpd_12m_unsecured_Agg_month,percent_90_above_dpd_12m_unsecured_Agg_month,percent_1_30_dpd_24m_all_Agg_month,percent_30_90_dpd_24m_all_Agg_month,percent_90_above_dpd_24m_all_Agg_month,percent_1_30_dpd_24m_secured_Agg_month,percent_30_90_dpd_24m_secured_Agg_month,percent_90_above_dpd_24m_secured_Agg_month,percent_1_30_dpd_24m_unsecured_Agg_month,percent_30_90_dpd_24m_unsecured_Agg_month,percent_90_above_dpd_24m_unsecured_Agg_month,collateral_loan_count_12m,total_loan_count_12m,collateral_loan_pct_12m,collateral_loan_count_24m,total_loan_count_24m,collateral_loan_pct_24m
0,FSTNLALONS000005474039,Apr-2026,1,0,1,0,0,0,0,0,1,1,1,1,0,0,0,1,1,1,0.343750,0.0,0.343750,0.000000,0.0,0.0,0.0,0.0,1.000000,0.185714,0.028571,0.257143,0.000000,0.0,0.0,0.040000,0.08,0.720000,1.0,3.0,0.333333,1,5,0.200000
1,FSTNLALONS000005407091,Apr-2026,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.00,0.000000,1.0,1.0,1.000000,1,2,0.500000
2,FSTNLALONS000005551172,Apr-2026,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.006993,0.000000,0.000000,0.009804,0.0,0.0,0.000000,0.00,0.000000,7.0,9.0,0.777778,10,12,0.833333
3,FSTNLALONS000005408908,Apr-2026,1,0,1,1,0,0,0,0,1,1,0,1,1,0,0,1,0,1,0.012658,0.0,0.139241,0.015625,0.0,0.0,0.0,0.0,0.733333,0.010526,0.000000,0.121053,0.006579,0.0,0.0,0.026316,0.00,0.605263,15.0,17.0,0.882353,16,19,0.842105
4,FSTNLALONS000005469099,Apr-2026,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.065574,0.000000,0.000000,0.181818,0.0,0.0,0.000000,0.00,0.000000,1.0,4.0,0.250000,1,5,0.200000

In [225]:
master_O01.columns

Index(['Unnamed: 0', 'CREDT-RPT-ID', 'LOS-APP-ID', 'CANDIDATE - ID',
       'CUSTOMER ID/MBR ID', 'BRANCH', 'KENDRA', 'SELF-INDICATOR',
       'MATCH-TYPE', 'ACC-NUM', 'CREDIT-GRANTOR', 'acct_type',
       'CONTRIBUTOR-TYPE', 'DATE-REPORTED', 'OWNERSHIP-IND', 'account_status',
       'DISBURSED-DT', 'CLOSE-DT', 'LAST-PAYMENT-DATE',
       'CREDIT-LIMIT/SANC AMT', 'disbursed_amt', ' INSTALLMENT-AMT',
       'current_bal', 'INSTALLMENT-FREQUENCY', 'WRITE-OFF-DATE', 'overdue_amt',
       ' WRITE-OFF-AMT', 'asset_class', ' ACCOUNT-REMARKS', 'LINKED-ACCOUNTS',
       'date_hist', 'dpd_hist', 'ASSET CLASS - HIST ', 'HIGH CRD - HIST ',
       'CUR BAL - HIST ', 'DAS - HIST ', 'AMT OVERDUE - HIST ',
       'AMT PAID - HIST ', 'INCOME ', ' INCOME INDICATOR ', 'TENURE ',
       ' OCCUPATION', 'Unnamed: 41', 'masked_loan_id', 'loan_number',
       'applicant_type', 'person_id', 'applicant_role'],
      dtype='str')

In [226]:
mapper = master_O01[['loan_number','masked_loan_id']].drop_duplicates()

In [228]:
mapper.head()

                loan_number   masked_loan_id
95   FSTNLALONS000005474039  LN_MRl5hrDqARI=
146  FSTNLALONS000005407091  LN_Pp2Vr6oGcNU=
150  FSTNLALONS000005551172  LN_W5h9O3eDWkw=
205  FSTNLALONS000005408908  LN_exut-M6aN5A=
288  FSTNLALONS000005469099  LN_T3B4gSeebKY=

In [229]:
feat_df.shape

(157542, 44)

In [230]:
feat_df_merged = feat_df.merge(mapper,on='loan_number',how='inner')

In [231]:
feat_df_merged.shape

(157542, 45)

# Merging the bounce and bureau_features

In [222]:
features.head()

,masked_loan_id,bounces_last_30d,bounces_last_60d,bounces_last_90d,bounces_last_180d,bounces_last_270d
0,LN_GlRWLuleCfo=,0.0,1,1,1,1
1,LN_YJDgotY4Ucc=,0.0,1,1,1,1
2,LN_ifhPIOkwq74=,0.0,0,0,0,0
3,LN_GmK89VbaOag=,0.0,0,0,0,0
4,LN__Pd6aMOmhbY=,0.0,0,0,0,0

In [232]:
feat_df_merged.head()

,loan_number,as_of_month,ever_1_30_dpd_12m_all,ever_30_90_dpd_12m_all,ever_90_above_dpd_12m_all,ever_1_30_dpd_12m_secured,ever_30_90_dpd_12m_secured,ever_90_above_dpd_12m_secured,ever_1_30_dpd_12m_unsecured,ever_30_90_dpd_12m_unsecured,ever_90_above_dpd_12m_unsecured,ever_1_30_dpd_24m_all,ever_30_90_dpd_24m_all,ever_90_above_dpd_24m_all,ever_1_30_dpd_24m_secured,ever_30_90_dpd_24m_secured,ever_90_above_dpd_24m_secured,ever_1_30_dpd_24m_unsecured,ever_30_90_dpd_24m_unsecured,ever_90_above_dpd_24m_unsecured,percent_1_30_dpd_12m_all_Agg_month,percent_30_90_dpd_12m_all_Agg_month,percent_90_above_dpd_12m_all_Agg_month,percent_1_30_dpd_12m_secured_Agg_month,percent_30_90_dpd_12m_secured_Agg_month,percent_90_above_dpd_12m_secured_Agg_month,percent_1_30_dpd_12m_unsecured_Agg_month,percent_30_90_dpd_12m_unsecured_Agg_month,percent_90_above_dpd_12m_unsecured_Agg_month,percent_1_30_dpd_24m_all_Agg_month,percent_30_90_dpd_24m_all_Agg_month,percent_90_above_dpd_24m_all_Agg_month,percent_1_30_dpd_24m_secured_Agg_month,percent_30_90_dpd_24m_secured_Agg_month,percent_90_above_dpd_24m_secured_Agg_month,percent_1_30_dpd_24m_unsecured_Agg_month,percent_30_90_dpd_24m_unsecured_Agg_month,percent_90_above_dpd_24m_unsecured_Agg_month,collateral_loan_count_12m,total_loan_count_12m,collateral_loan_pct_12m,collateral_loan_count_24m,total_loan_count_24m,collateral_loan_pct_24m,masked_loan_id
0,FSTNLALONS000005474039,Apr-2026,1,0,1,0,0,0,0,0,1,1,1,1,0,0,0,1,1,1,0.343750,0.0,0.343750,0.000000,0.0,0.0,0.0,0.0,1.000000,0.185714,0.028571,0.257143,0.000000,0.0,0.0,0.040000,0.08,0.720000,1.0,3.0,0.333333,1,5,0.200000,LN_MRl5hrDqARI=
1,FSTNLALONS000005407091,Apr-2026,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.00,0.000000,1.0,1.0,1.000000,1,2,0.500000,LN_Pp2Vr6oGcNU=
2,FSTNLALONS000005551172,Apr-2026,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.006993,0.000000,0.000000,0.009804,0.0,0.0,0.000000,0.00,0.000000,7.0,9.0,0.777778,10,12,0.833333,LN_W5h9O3eDWkw=
3,FSTNLALONS000005408908,Apr-2026,1,0,1,1,0,0,0,0,1,1,0,1,1,0,0,1,0,1,0.012658,0.0,0.139241,0.015625,0.0,0.0,0.0,0.0,0.733333,0.010526,0.000000,0.121053,0.006579,0.0,0.0,0.026316,0.00,0.605263,15.0,17.0,0.882353,16,19,0.842105,LN_exut-M6aN5A=
4,FSTNLALONS000005469099,Apr-2026,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.065574,0.000000,0.000000,0.181818,0.0,0.0,0.000000,0.00,0.000000,1.0,4.0,0.250000,1,5,0.200000,LN_T3B4gSeebKY=

In [233]:
print(features['masked_loan_id'].nunique())

158461

In [234]:
print(feat_df_merged['masked_loan_id'].nunique())

157542

In [236]:
bureau_bounce_features = features.merge(feat_df_merged,on='masked_loan_id',how='left')

In [237]:
features.shape

(158461, 6)

In [238]:
bureau_bounce_features.shape

(158461, 50)

In [241]:
bureau_bounce_features[bureau_bounce_features['loan_number'].isna()].shape

(919, 50)

In [243]:
919/158461
# No bureau customers

0.005799534270262084

# Running bounce + bureau model

In [244]:
bureau_bounce_features.columns

Index(['masked_loan_id', 'bounces_last_30d', 'bounces_last_60d',
       'bounces_last_90d', 'bounces_last_180d', 'bounces_last_270d',
       'loan_number', 'as_of_month', 'ever_1_30_dpd_12m_all',
       'ever_30_90_dpd_12m_all', 'ever_90_above_dpd_12m_all',
       'ever_1_30_dpd_12m_secured', 'ever_30_90_dpd_12m_secured',
       'ever_90_above_dpd_12m_secured', 'ever_1_30_dpd_12m_unsecured',
       'ever_30_90_dpd_12m_unsecured', 'ever_90_above_dpd_12m_unsecured',
       'ever_1_30_dpd_24m_all', 'ever_30_90_dpd_24m_all',
       'ever_90_above_dpd_24m_all', 'ever_1_30_dpd_24m_secured',
       'ever_30_90_dpd_24m_secured', 'ever_90_above_dpd_24m_secured',
       'ever_1_30_dpd_24m_unsecured', 'ever_30_90_dpd_24m_unsecured',
       'ever_90_above_dpd_24m_unsecured', 'percent_1_30_dpd_12m_all_Agg_month',
       'percent_30_90_dpd_12m_all_Agg_month',
       'percent_90_above_dpd_12m_all_Agg_month',
       'percent_1_30_dpd_12m_secured_Agg_month',
       'percent_30_90_dpd_12m_secured_Agg_month',
       'percent_90_above_dpd_12m_secured_Agg_month',
       'percent_1_30_dpd_12m_unsecured_Agg_month',
       'percent_30_90_dpd_12m_unsecured_Agg_month',
       'percent_90_above_dpd_12m_unsecured_Agg_month',
       'percent_1_30_dpd_24m_all_Agg_month',
       'percent_30_90_dpd_24m_all_Agg_month',
       'percent_90_above_dpd_24m_all_Agg_month',
       'percent_1_30_dpd_24m_secured_Agg_month',
       'percent_30_90_dpd_24m_secured_Agg_month',
       'percent_90_above_dpd_24m_secured_Agg_month',
       'percent_1_30_dpd_24m_unsecured_Agg_month',
       'percent_30_90_dpd_24m_unsecured_Agg_month',
       'percent_90_above_dpd_24m_unsecured_Agg_month',
       'collateral_loan_count_12m', 'total_loan_count_12m',
       'collateral_loan_pct_12m', 'collateral_loan_count_24m',
       'total_loan_count_24m', 'collateral_loan_pct_24m'],
      dtype='str')

In [245]:
import pickle

MODEL_DIR = f'{BASE_PATH}/models'

# ============================================================
# LOAD MODELS
# ============================================================
with open(f'{MODEL_DIR}/model_bounce_bureau.pkl', 'rb') as f:
    model = pickle.load(f)

with open(f'{MODEL_DIR}/model_bureau_only.pkl', 'rb') as f:
    model_bureau = pickle.load(f)

with open(f'{MODEL_DIR}/model_bounce_only.pkl', 'rb') as f:
    model_bounce = pickle.load(f)

# ============================================================
# LOAD FEATURE COLUMN LISTS
# ============================================================
with open(f'{MODEL_DIR}/feature_cols_bounce_bureau.pkl', 'rb') as f:
    feature_cols = pickle.load(f)

with open(f'{MODEL_DIR}/feature_cols_bureau_only.pkl', 'rb') as f:
    bureau_feature_cols = pickle.load(f)

with open(f'{MODEL_DIR}/feature_cols_bounce_only.pkl', 'rb') as f:
    bounce_feature_cols = pickle.load(f)

print("Models loaded:")
for name, mdl in [('model_bounce_bureau', model), ('model_bureau_only', model_bureau), ('model_bounce_only', model_bounce)]:
    print(f"  {name}: {type(mdl).__name__} ✅  (n_estimators={mdl.n_estimators}, max_depth={mdl.max_depth})")

print(f"\nFeature set sizes:")
print(f"  bounce_bureau : {len(feature_cols)}")
print(f"  bureau_only   : {len(bureau_feature_cols)}")
print(f"  bounce_only   : {len(bounce_feature_cols)}")

# ============================================================
# SCORE bureau_bounce_features
# ============================================================
# Check all required features exist
for label, cols in [('bounce_bureau', feature_cols), ('bureau_only', bureau_feature_cols), ('bounce_only', bounce_feature_cols)]:
    missing = set(cols) - set(bureau_bounce_features.columns)
    print(f"\n  [{label}] Missing features: {len(missing)} {'✅' if len(missing) == 0 else f'❌ {missing}'}")

# Score
X_all      = bureau_bounce_features[feature_cols]
X_bureau   = bureau_bounce_features[bureau_feature_cols]
X_bounce   = bureau_bounce_features[bounce_feature_cols]

bureau_bounce_features['score_bounce_bureau'] = model.predict_proba(X_all)[:, 1]
bureau_bounce_features['score_bureau_only']   = model_bureau.predict_proba(X_bureau)[:, 1]
bureau_bounce_features['score_bounce_only']   = model_bounce.predict_proba(X_bounce)[:, 1]

print("\nScore summary:")
print(bureau_bounce_features[['score_bounce_bureau', 'score_bureau_only', 'score_bounce_only']].describe().round(4))

Models loaded:
  model_bounce_bureau: XGBClassifier ✅  (n_estimators=100, max_depth=4)
  model_bureau_only: XGBClassifier ✅  (n_estimators=100, max_depth=4)
  model_bounce_only: XGBClassifier ✅  (n_estimators=100, max_depth=4)

Feature set sizes:
  bounce_bureau : 47
  bureau_only   : 42
  bounce_only   : 5

  [bounce_bureau] Missing features: 0 ✅

  [bureau_only] Missing features: 0 ✅

  [bounce_only] Missing features: 0 ✅

Score summary:
       score_bounce_bureau  score_bureau_only  score_bounce_only
count          158461.0000        158461.0000        158461.0000
mean                0.3668             0.3826             0.3817
std                 0.2239             0.1517             0.1958
min                 0.0842             0.1539             0.1824
25%                 0.1244             0.2930             0.1824
50%                 0.3628             0.3173             0.3742
75%                 0.6001             0.4238             0.6099
max                 0.9991             0.9992             0.9583

# Applying test decile bands on bureau+bounce from 
- https://docs.google.com/spreadsheets/d/1n8TtYHvXVcEwsymr40GtZ29wzrQVh2uCrPnka7xB-I0/edit?gid=1797364379#gid=1797364379

In [251]:
import pandas as pd
import numpy as np

# ============================================================
# EXACT BAND BOUNDARIES
# ============================================================
BAND_BINS   = [0.072, 0.116, 0.124, 0.126, 0.195, 0.354, 0.686, 0.942, 0.980, 0.995, 1.000]
BAND_LABELS = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

# ============================================================
# SCORE
# ============================================================
X = bureau_bounce_features[feature_cols]
bureau_bounce_features['score_bounce_bureau'] = model.predict_proba(X)[:, 1]

# ============================================================
# ASSIGN BANDS
# ============================================================
bureau_bounce_features['band'] = pd.cut(
    bureau_bounce_features['score_bounce_bureau'],
    bins           = BAND_BINS,
    labels         = BAND_LABELS,
    right          = True,
    include_lowest = True
)

# Loans outside band range → Band 99 (review separately)
bureau_bounce_features['band'] = bureau_bounce_features['band'].cat.add_categories(99)
bureau_bounce_features['band'] = bureau_bounce_features['band'].fillna(99)

# ============================================================
# DISTRIBUTION CHECK
# ============================================================
total    = len(bureau_bounce_features)
no_score = bureau_bounce_features['score_bounce_bureau'].isna().sum()

dist = (
    bureau_bounce_features
    .groupby('band', observed=False)['masked_loan_id']
    .count()
    .reset_index()
    .rename(columns={'masked_loan_id': 'count'})
)
dist['% Loans'] = (dist['count'] / total * 100).round(2)

print(f"\nInference — Bounce + Bureau Model | Apr-2026")
print(f"Total loans : {total:,}  |  noScore : {no_score:,}")
print(f"{'='*40}")
print(dist.to_string(index=False))
print(f"\nScore summary:")
print(bureau_bounce_features['score_bounce_bureau'].describe().round(4))

Inference — Bounce + Bureau Model | Apr-2026
Total loans : 158,461  |  noScore : 0
========================================
band  count  % Loans
  10  21896    13.82
   9   4306     2.72
   8  22284    14.06
   7  14903     9.40
   6  14921     9.42
   5  77104    48.66
   4   2118     1.34
   3    532     0.34
   2      0     0.00
   1    397     0.25
  99      0     0.00

Score summary:
count    158461.0000
mean          0.3668
std           0.2239
min           0.0842
25%           0.1244
50%           0.3628
75%           0.6001
max           0.9991
Name: score_bounce_bureau, dtype: float64

In [252]:
# ============================================================
# SCORE DISTRIBUTION DIAGNOSTICS
# ============================================================

# 1. Score histogram to see where mass is concentrated
print("Score percentile distribution:")
percentiles = [1, 5, 10, 25, 50, 75, 90, 95, 99]
print(
    bureau_bounce_features['score_bounce_bureau']
    .quantile([p/100 for p in percentiles])
    .rename(lambda x: f"p{int(x*100)}")
    .round(4)
)

# 2. How many loans fall in each band vs training expectation (~10% each)
print("\nBand distribution vs training expectation:")
total = len(bureau_bounce_features)
training_pct = {1: 0.03, 2: 0.25, 3: 1.18, 4: 5.0, 5: 11.07,
                6: 15.13, 7: 16.49, 8: 16.88, 9: 16.92, 10: 17.04}
dist = (
    bureau_bounce_features
    .groupby('band', observed=False)['masked_loan_id']
    .count()
    .reset_index()
    .rename(columns={'masked_loan_id': 'count'})
)
dist['% Loans (Apr-2026)'] = (dist['count'] / total * 100).round(2)
dist['% Loans (Training)'] = dist['band'].map(training_pct).fillna(0)
dist['Shift']              = (dist['% Loans (Apr-2026)'] - dist['% Loans (Training)']).round(2)
print(dist.to_string(index=False))

# 3. Check if Five Star loans tend to be lower risk (expected given their customer profile)
print(f"\nMedian score          : {bureau_bounce_features['score_bounce_bureau'].median():.4f}")
print(f"% loans scoring > 0.5 : {(bureau_bounce_features['score_bounce_bureau'] > 0.5).mean()*100:.1f}%")
print(f"% loans scoring > 0.9 : {(bureau_bounce_features['score_bounce_bureau'] > 0.9).mean()*100:.1f}%")

Score percentile distribution:
p1     0.0978
p5     0.1040
p10    0.1160
p25    0.1244
p50    0.3628
p75    0.6001
p90    0.6236
p95    0.6428
p99    0.7705
Name: score_bounce_bureau, dtype: float64

Band distribution vs training expectation:
band  count  % Loans (Apr-2026)  % Loans (Training)  Shift
  10  21896               13.82               17.04  -3.22
   9   4306                2.72               16.92 -14.20
   8  22284               14.06               16.88  -2.82
   7  14903                9.40               16.49  -7.09
   6  14921                9.42               15.13  -5.71
   5  77104               48.66               11.07  37.59
   4   2118                1.34                5.00  -3.66
   3    532                0.34                1.18  -0.84
   2      0                0.00                0.25  -0.25
   1    397                0.25                0.03   0.22
  99      0                0.00                0.00   0.00

Median score          : 0.3628
% loans scoring > 0.5 : 39.9%
% loans scoring > 0.9 : 0.6%

In [249]:
# ============================================================
# FEATURE DISTRIBUTION DIAGNOSTICS
# ============================================================

# 1. How many loans have zero bureau history (all bureau features = 0)
bureau_feats  = [c for c in feature_cols if 'dpd' in c or 'collateral' in c]
bounce_feats  = [c for c in feature_cols if 'bounces' in c]

bureau_all_zero = (bureau_bounce_features[bureau_feats] == 0).all(axis=1).sum()
bounce_all_zero = (bureau_bounce_features[bounce_feats] == 0).all(axis=1).sum()

print("=== Zero-feature loans ===")
print(f"  Loans with ALL bureau features = 0 : {bureau_all_zero:,}  ({bureau_all_zero/len(bureau_bounce_features)*100:.1f}%)")
print(f"  Loans with ALL bounce features = 0 : {bounce_all_zero:,}  ({bounce_all_zero/len(bureau_bounce_features)*100:.1f}%)")
print(f"  Both zero                          : {((bureau_bounce_features[bureau_feats]==0).all(axis=1) & (bureau_bounce_features[bounce_feats]==0).all(axis=1)).sum():,}")

# 2. Feature means — are Five Star loans genuinely cleaner?
print("\n=== Feature means (Five Star Apr-2026) ===")
print(bureau_bounce_features[feature_cols].mean().round(4).to_string())

# 3. Score distribution of loans with zero bureau vs non-zero bureau
has_bureau = (bureau_bounce_features[bureau_feats] != 0).any(axis=1)
print("\n=== Score by bureau data availability ===")
print(
    bureau_bounce_features
    .assign(has_bureau_data=has_bureau)
    .groupby('has_bureau_data')['score_bounce_bureau']
    .describe().round(4)
)

# 4. Bounce feature distribution
print("\n=== Bounce feature distribution ===")
print(bureau_bounce_features[bounce_feats].describe().round(4).to_string())

=== Zero-feature loans ===
  Loans with ALL bureau features = 0 : 0  (0.0%)
  Loans with ALL bounce features = 0 : 72,411  (45.7%)
  Both zero                          : 0

=== Feature means (Five Star Apr-2026) ===
bounces_last_30d                                0.0000
bounces_last_60d                                0.4588
bounces_last_90d                                0.9257
bounces_last_180d                               0.9257
bounces_last_270d                               0.9257
ever_1_30_dpd_12m_all                           0.2388
ever_30_90_dpd_12m_all                          0.1692
ever_90_above_dpd_12m_all                       0.2472
ever_1_30_dpd_12m_secured                       0.1364
ever_30_90_dpd_12m_secured                      0.0812
ever_90_above_dpd_12m_secured                   0.0523
ever_1_30_dpd_12m_unsecured                     0.1270
ever_30_90_dpd_12m_unsecured                    0.1000
ever_90_above_dpd_12m_unsecured                 0.2087
ever_1_30_dpd_24m_all                           0.3626
ever_30_90_dpd_24m_all                          0.2646
ever_90_above_dpd_24m_all                       0.2883
ever_1_30_dpd_24m_secured                       0.2173
ever_30_90_dpd_24m_secured                      0.1344
ever_90_above_dpd_24m_secured                   0.0776
ever_1_30_dpd_24m_unsecured                     0.2076
ever_30_90_dpd_24m_unsecured                    0.1625
ever_90_above_dpd_24m_unsecured                 0.2343
percent_1_30_dpd_12m_all_Agg_month              0.0211
percent_30_90_dpd_12m_all_Agg_month             0.0173
percent_90_above_dpd_12m_all_Agg_month          0.0864
percent_1_30_dpd_12m_secured_Agg_month          0.0178
percent_30_90_dpd_12m_secured_Agg_month         0.0126
percent_90_above_dpd_12m_secured_Agg_month      0.0131
percent_1_30_dpd_12m_unsecured_Agg_month        0.0167
percent_30_90_dpd_12m_unsecured_Agg_month       0.0148
percent_90_above_dpd_12m_unsecured_Agg_month    0.1328
percent_1_30_dpd_24m_all_Agg_month              0.0239
percent_30_90_dpd_24m_all_Agg_month             0.0187
percent_90_above_dpd_24m_all_Agg_month          0.0790
percent_1_30_dpd_24m_secured_Agg_month          0.0209
percent_30_90_dpd_24m_secured_Agg_month         0.0143
percent_90_above_dpd_24m_secured_Agg_month      0.0137
percent_1_30_dpd_24m_unsecured_Agg_month        0.0186
percent_30_90_dpd_24m_unsecured_Agg_month       0.0156
percent_90_above_dpd_24m_unsecured_Agg_month    0.1192
collateral_loan_count_12m                       2.6559
total_loan_count_12m                            4.5819
collateral_loan_pct_12m                         0.6954
collateral_loan_count_24m                       3.3992
total_loan_count_24m                            6.1191
collateral_loan_pct_24m                         0.6700

=== Score by bureau data availability ===
                    count    mean     std     min     25%     50%     75%  \
has_bureau_data
True             158461.0  0.3668  0.2239  0.0842  0.1244  0.3628  0.6001

                    max
has_bureau_data
True             0.9991

=== Bounce feature distribution ===
       bounces_last_30d  bounces_last_60d  bounces_last_90d  bounces_last_180d  bounces_last_270d
count       158461.0000       158461.0000       158461.0000        158461.0000        158461.0000
mean             0.0000            0.4588            0.9257             0.9257             0.9257
std              0.0062            0.4984            0.9133             0.9133             0.9133
min              0.0000            0.0000            0.0000             0.0000             0.0000
25%              0.0000            0.0000            0.0000             0.0000             0.0000
50%              0.0000            0.0000            1.0000             1.0000             1.0000
75%              0.0000            1.0000            2.0000             2.0000             2.0000
max              1.0000            2.0000            3.0000             3.0000             3.0000

In [250]:
# ============================================================
# BUREAU FEATURE ZERO-RICHNESS ANALYSIS
# ============================================================

ever_feats    = [c for c in feature_cols if c.startswith('ever_')]
pct_feats     = [c for c in feature_cols if c.startswith('percent_')]
collat_feats  = [c for c in feature_cols if 'collateral' in c or 'total_loan_count' in c]
bureau_feats  = ever_feats + pct_feats + collat_feats

df = bureau_bounce_features.copy()

# ── 1. All bureau features = 0 ────────────────────────────────
df['all_ever_zero']   = (df[ever_feats]   == 0).all(axis=1)
df['all_pct_zero']    = (df[pct_feats]    == 0).all(axis=1)
df['all_collat_zero'] = (df[collat_feats] == 0).all(axis=1)
df['all_bureau_zero'] = (df[bureau_feats] == 0).all(axis=1)

n = len(df)
print("=== Bureau Feature Sparsity ===")
print(f"  All ever_*  features = 0 : {df['all_ever_zero'].sum():>7,}  ({df['all_ever_zero'].mean()*100:.1f}%)")
print(f"  All pct_*   features = 0 : {df['all_pct_zero'].sum():>7,}  ({df['all_pct_zero'].mean()*100:.1f}%)")
print(f"  All collat  features = 0 : {df['all_collat_zero'].sum():>7,}  ({df['all_collat_zero'].mean()*100:.1f}%)")
print(f"  ALL bureau  features = 0 : {df['all_bureau_zero'].sum():>7,}  ({df['all_bureau_zero'].mean()*100:.1f}%)")

# ── 2. Count how many bureau features are non-zero per loan ───
df['n_nonzero_bureau'] = (df[bureau_feats] != 0).sum(axis=1)
print("\n=== Non-zero bureau feature count per loan ===")
print(df['n_nonzero_bureau'].describe().round(2))
print(f"\n  Loans with 0  non-zero bureau features : {(df['n_nonzero_bureau']==0).sum():,}  ({(df['n_nonzero_bureau']==0).mean()*100:.1f}%)")
print(f"  Loans with <=3 non-zero bureau features : {(df['n_nonzero_bureau']<=3).sum():,}  ({(df['n_nonzero_bureau']<=3).mean()*100:.1f}%)")
print(f"  Loans with <=5 non-zero bureau features : {(df['n_nonzero_bureau']<=5).sum():,}  ({(df['n_nonzero_bureau']<=5).mean()*100:.1f}%)")

# ── 3. Score distribution: thin bureau vs rich bureau ─────────
df['bureau_richness'] = pd.cut(
    df['n_nonzero_bureau'],
    bins   = [-1, 0, 5, 15, df['n_nonzero_bureau'].max()],
    labels = ['0 (no bureau)', '1-5 (thin)', '6-15 (moderate)', '16+ (rich)']
)
print("\n=== Score by bureau richness ===")
print(
    df.groupby('bureau_richness', observed=False)['score_bounce_bureau']
    .agg(['count', 'mean', 'median', 'std'])
    .rename(columns={'count':'n', 'mean':'mean_score', 'median':'median_score', 'std':'std_score'})
    .round(4)
)

# ── 4. Band distribution by bureau richness ───────────────────
print("\n=== Band distribution by bureau richness ===")
print(
    df.groupby(['bureau_richness', 'band'], observed=False)['masked_loan_id']
    .count()
    .unstack('band', fill_value=0)
)

=== Bureau Feature Sparsity ===
  All ever_*  features = 0 :  83,436  (52.7%)
  All pct_*   features = 0 :  83,436  (52.7%)
  All collat  features = 0 :       0  (0.0%)
  ALL bureau  features = 0 :       0  (0.0%)

=== Non-zero bureau feature count per loan ===
count    158461.00
mean         12.79
std           9.06
min           3.00
25%           6.00
50%           6.00
75%          18.00
max          42.00
Name: n_nonzero_bureau, dtype: float64

  Loans with 0  non-zero bureau features : 0  (0.0%)
  Loans with <=3 non-zero bureau features : 1  (0.0%)
  Loans with <=5 non-zero bureau features : 1  (0.0%)

=== Score by bureau richness ===
                      n  mean_score  median_score  std_score
bureau_richness
0 (no bureau)         0         NaN           NaN        NaN
1-5 (thin)            1      0.1257        0.1257        NaN
6-15 (moderate)  115652      0.3221        0.2167     0.2158
16+ (rich)        42808      0.4874        0.5747     0.1995

=== Band distribution by bureau richness ===
band                10     9      8     7     6      5     4    3  2    1  99
bureau_richness
0 (no bureau)        0     0      0     0     0      0     0    0  0    0   0
1-5 (thin)           0     0      1     0     0      0     0    0  0    0   0
6-15 (moderate)  21779  4175  22246  9425  8762  48616   649    0  0    0   0
16+ (rich)         117   131     37  5478  6159  28488  1469  532  0  397   0

# Bureau only model comparison

In [254]:
import pandas as pd
import numpy as np

# ============================================================
# BAND BOUNDARIES
# ============================================================
BB_BINS   = [0.072, 0.116, 0.124, 0.126, 0.195, 0.354, 0.686, 0.942, 0.980, 0.995, 1.000]
BB_LABELS = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

BUREAU_BINS   = [0.130, 0.272, 0.299, 0.317, 0.339, 0.430, 0.553, 0.809, 0.975, 0.999]
BUREAU_LABELS = [10, 9, 8, 6, 5, 4, 3, 2, 1]   # Band 7+8 merged → drop one label

def score_and_band(df, model, feature_cols, score_col, bins, labels, model_label):
    # Score
    X = df[feature_cols]
    df[score_col] = model.predict_proba(X)[:, 1]

    # Band
    band_col = score_col.replace('score_', 'band_')
    df[band_col] = pd.cut(
        df[score_col],
        bins           = bins,
        labels         = labels,
        right          = True,
        include_lowest = True
    )
    df[band_col] = df[band_col].cat.add_categories(99)
    df[band_col] = df[band_col].fillna(99)

    # Distribution
    total    = len(df)
    no_score = df[score_col].isna().sum()
    dist = (
        df.groupby(band_col, observed=False)['masked_loan_id']
        .count()
        .reset_index()
        .rename(columns={'masked_loan_id': 'count', band_col: 'band'})
    )
    dist['% Loans'] = (dist['count'] / total * 100).round(2)

    print(f"\nInference — {model_label} | Apr-2026")
    print(f"Total loans : {total:,}  |  noScore : {no_score:,}")
    print(f"{'='*45}")
    print(dist.to_string(index=False))
    print(f"\nScore summary:")
    print(df[score_col].describe().round(4))

    return df

# ============================================================
# BOUNCE + BUREAU MODEL
# ============================================================
bureau_bounce_features = score_and_band(
    df           = bureau_bounce_features,
    model        = model,
    feature_cols = feature_cols,
    score_col    = 'score_bounce_bureau',
    bins         = BB_BINS,
    labels       = BB_LABELS,
    model_label  = 'Bounce + Bureau Model'
)

# ============================================================
# BUREAU ONLY MODEL
# ============================================================
bureau_bounce_features = score_and_band(
    df           = bureau_bounce_features,
    model        = model_bureau,
    feature_cols = bureau_feature_cols,
    score_col    = 'score_bureau_only',
    bins         = BUREAU_BINS,
    labels       = BUREAU_LABELS,
    model_label  = 'Bureau Only Model'
)

Inference — Bounce + Bureau Model | Apr-2026
Total loans : 158,461  |  noScore : 0
=============================================
band  count  % Loans
  10  21896    13.82
   9   4306     2.72
   8  22284    14.06
   7  14903     9.40
   6  14921     9.42
   5  77104    48.66
   4   2118     1.34
   3    532     0.34
   2      0     0.00
   1    397     0.25
  99      0     0.00

Score summary:
count    158461.0000
mean          0.3668
std           0.2239
min           0.0842
25%           0.1244
50%           0.3628
75%           0.6001
max           0.9991
Name: score_bounce_bureau, dtype: float64

Inference — Bureau Only Model | Apr-2026
Total loans : 158,461  |  noScore : 0
=============================================
band  count  % Loans
  10  21981    13.87
   9  21780    13.74
   8  14267     9.00
   6  36898    23.29
   5  25264    15.94
   4  20890    13.18
   3  12117     7.65
   2   4204     2.65
   1    141     0.09
  99    919     0.58

Score summary:
count    158461.0000
mean          0.3826
std           0.1517
min           0.1539
25%           0.2930
50%           0.3173
75%           0.4238
max           0.9992
Name: score_bureau_only, dtype: float64

# Saving all model scores

In [255]:
BASE_PATH

'/Users/shiva/Downloads/Five_star_customer_data'

In [256]:
# ============================================================
# SAVE MODEL SCORES
# ============================================================

scores_df = bureau_bounce_features[[
    'masked_loan_id',
    'score_bounce_bureau',   # PD — Bounce + Bureau model
    'band_bounce_bureau',    # Band — Bounce + Bureau model
    'score_bureau_only',     # PD — Bureau Only model
    'band_bureau_only',      # Band — Bureau Only model
]].copy()

scores_df = scores_df.rename(columns={
    'score_bounce_bureau' : 'pd_bounce_bureau',
    'score_bureau_only'   : 'pd_bureau_only',
})

scores_df['as_of_date'] = 'Apr-2026'

print(f"Scores shape : {scores_df.shape}")
print(f"\nSample:")
print(scores_df.head())
print(f"\nScore summary:")
print(scores_df[['pd_bounce_bureau', 'pd_bureau_only']].describe().round(4))

# Save
scores_df.to_csv(f'{BASE_PATH}/five_star_scores_apr2026.csv', index=False)
scores_df.to_parquet(f'{BASE_PATH}/five_star_scores_apr2026.parquet', index=False)

print(f"\nSaved: five_star_scores_apr2026.csv / .parquet")

Scores shape : (158461, 6)

Sample:
    masked_loan_id  pd_bounce_bureau band_bounce_bureau  pd_bureau_only  \
0  LN_GlRWLuleCfo=          0.449721                  5        0.446284
1  LN_YJDgotY4Ucc=          0.409868                  5        0.317300
2  LN_ifhPIOkwq74=          0.133854                  7        0.335655
3  LN_GmK89VbaOag=          0.334976                  6        0.667363
4  LN__Pd6aMOmhbY=          0.124444                  8        0.306326

  band_bureau_only as_of_date
0                4   Apr-2026
1                6   Apr-2026
2                6   Apr-2026
3                3   Apr-2026
4                8   Apr-2026

Score summary:
       pd_bounce_bureau  pd_bureau_only
count       158461.0000     158461.0000
mean             0.3668          0.3826
std              0.2239          0.1517
min              0.0842          0.1539
25%              0.1244          0.2930
50%              0.3628          0.3173
75%              0.6001          0.4238
max              0.9991          0.9992

Saved: five_star_scores_apr2026.csv / .parquet

In [258]:
scores_df.head()

,masked_loan_id,pd_bounce_bureau,band_bounce_bureau,pd_bureau_only,band_bureau_only,as_of_date
0,LN_GlRWLuleCfo=,0.449721,5,0.446284,4,Apr-2026
1,LN_YJDgotY4Ucc=,0.409868,5,0.317300,6,Apr-2026
2,LN_ifhPIOkwq74=,0.133854,7,0.335655,6,Apr-2026
3,LN_GmK89VbaOag=,0.334976,6,0.667363,3,Apr-2026
4,LN__Pd6aMOmhbY=,0.124444,8,0.306326,8,Apr-2026

In [259]:
scores_df.shape

(158461, 6)